name: BigB-website Actions CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
         html_file: 'index.html'
       
      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "./"
          
      - name: Build and deploy to GitHub Pages
        uses: EdricChan03/action-build-deploy-ghpages@v2.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

